### ISSUE TITLE
centos7 support wanted

### ISSUE THREAD

**Issue by KathrynMorgan** [containercraft/containercraft.github.io#1]
Developer support requires CentOS 7.x setup instructions

**Comment by trentfowler** [comment]
**Installing Jekyll with Ruby 2.3 in CentOS 7**

Jekyll doesn't work with the default 2.0 Ruby version that you currently get in the yum repos but you can use RVM to install 2.3 which works great with Jekyll. 

First Install Dependencies: 

`# yum install gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison iconv-devel sqlite-devel`

Install Ruby Version Manager: 

`# curl -sSL http://rvm.io/mpapis.asc | gpg --import -`
`# curl -L get.rvm.io | bash -s stable`

_Note: Use HTTP instead of HTTPS unlike source below._

Load RVM:

`# source /etc/profile.d/rvm.sh`
`# rvm reload`

Install Ruby 2.3: 

`# rvm install 2.3.3`

Check version installed and set as default:

`# rvm list`
_=> ruby-2.3.3_

`# rvm use 2.3.3 --default`

[Source](https://tecadmin.net/install-ruby-previous-stable-centos/)

Then just install Jekyll with RubyGems:

`# gem install jekyll`

`# gem install bundle`

**Comment by KathrynMorgan** [comment]
Adding the following to README.md


    
###### Centos 7.4
    1) $ lxc launch images:centos/7/amd64 trent-centos-t01 -p  physical-net
    2) $ lxc exec trent-centos-t01 bash
    3) $ yum install gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel openssl-devel make bzip2 autoconf automake libtool bison iconv-devel sqlite-devel which
    4) $ curl -sSL http://rvm.io/mpapis.asc | gpg --import -
    5) $ curl -L get.rvm.io | bash -s stable
    6) $ usermod -a -G rvm $USER_NAME 
    7) $ source /etc/profile.d/rvm.sh
    8) $ rvm reload
    9) $ rvm use 2.3.3 --default
    10)$ rvm list
    11)$ rvm use 2.3.3 --default

**Comment by KathrynMorgan** [comment]
Closing issue, centos support install guide feature request merged in commit 8160c8996761a777e47aa7fc7e8001f706082b0b
